name: Docker Publish

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

env:
  tag: latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          provenance: false
          tags: |
            ${{ github.repository }}:${{ env.tag }}
            ghcr.io/${{ github.repository }}:${{ env.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
